x-environment-vars: &env
  PUID: 1000
  PGID: 1000
  UMASK: 002
  TZ: Europe/Vilnius

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 8082:80
    volumes:
      - /opt/appdata/filebrowser:/config
      - /opt/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /opt/appdata:/srv/appdata
      - /data:/srv/data
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    environment:
      <<: *env
    ports:
      - 3000:3000
    volumes:
      - /opt/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    environment:
      <<: *env
    network_mode: host
    volumes:
      - /opt/appdata/home-assistant:/config
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 1010:80
    environment:
      TZ: 'Europe/Vilnius'
      WEBPASSWORD: ''
    volumes:
      - /opt/appdata/pihole:/etc/pihole
      - /opt/appdata/pihole/DNS:/etc/dnsmasq.d
# --- Monitoring ---
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/appdata/netdata/config:/etc/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
# --- Media ---
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 8096:8096
    volumes:
      - /opt/appdata/jellyfin:/config
      - /data/media:/data/media
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 5055:5055
    volumes:
      - /opt/appdata/jellyseer:/app/config
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 7878:7878
    volumes:
      - /opt/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 8989:8989
    volumes:
      - /opt/appdata/sonarr:/config
      - /data:/data
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 9696:9696
    volumes:
      - /opt/appdata/prowlarr:/config
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      <<: *env
    ports:
      - 8080:8080
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /data/usenet:/data/usenet:rw
  qflood:
    container_name: qflood
    image: cr.hotio.dev/hotio/qflood
    ports:
      - "8081:8080"
      - "3001:3000"
    environment:
      FLOOD_AUTH: false
      WEBUI_PORTS: 8081/tcp,8081/udp,3001/tcp,3001/udp
      <<: *env
    volumes:
      - /opt/appdata/qflood:/config
