version: "3.3"
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    volumes:
      - /opt/appdata/filebrowser:/config
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    ports:
      - 3000:3000
    volumes:
      - /opt/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/appdata/home-assistant:/config
# --- Monitoring ---
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    hostname: home
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/appdata/netdata/config:/etc/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
# --- Media ---
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /opt/appdata/jellyfin:/config
      - /data/media:/data/media
    ports:
      - 8096:8096
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius
    ports:
      - 5055:5055
    volumes:
      - /opt/appdata/jellyseer:/app/config
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /opt/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /opt/appdata/sonarr:/config
      - /data:/data
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /data/usenet:/data/usenet:rw
